# Generated by Django 3.2.3 on 2023-01-24 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='password')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('users-pic', 'users-pic'))),
                ('id_image', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('users-pic', 'users-pic'))),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('etlo_id', models.CharField(default=main.models.rand, editable=False, max_length=10, unique=True)),
                ('email_verification', models.BooleanField(default=False, null=True)),
                ('phone_verification', models.BooleanField(default=False, null=True)),
                ('image_verification', models.BooleanField(default=False, null=True)),
                ('id_verification', models.BooleanField(default=False, null=True)),
                ('image_verification_error', models.CharField(blank=True, max_length=150, null=True)),
                ('id_verification_error', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=main.models.PathRename('bankcard', 'bankcard'))),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=6, null=True)),
                ('sheba_code', models.CharField(max_length=3, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_icon', models.ImageField(upload_to=main.models.PathRename('bankicon', 'bankicon'))),
            ],
        ),
        migrations.CreateModel(
            name='BankSheba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('symbol', models.CharField(max_length=3, null=True)),
                ('dial_code', models.CharField(max_length=5, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('have_service', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': ' Countries ',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('symbol', models.CharField(max_length=3, null=True)),
                ('icon', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('to_irt', models.FloatField(null=True)),
                ('min_deposit', models.FloatField(null=True)),
                ('max_deposit', models.FloatField(null=True)),
                ('deposit_fee', models.CharField(max_length=30, null=True)),
                ('deposit_bank_fee', models.CharField(max_length=30, null=True)),
                ('min_withdraw', models.FloatField(null=True)),
                ('max_withdraw', models.FloatField(null=True)),
                ('withdraw_fee', models.CharField(max_length=30, null=True)),
                ('withdraw_bank_fee', models.CharField(max_length=30, null=True)),
                ('admin_address', models.CharField(max_length=64, null=True)),
                ('name_of_address', models.CharField(max_length=64, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='main.country')),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ' Currencies ',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Department ',
                'verbose_name_plural': ' Departments ',
            },
        ),
        migrations.CreateModel(
            name='DepositSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('can_do', models.CharField(max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bankcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bankcard')),
                ('banksheba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.banksheba')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.FloatField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(default=1)),
                ('amount', models.FloatField()),
                ('details', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=30, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('city', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='main.country')),
            ],
            options={
                'verbose_name_plural': ' States ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.department')),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Department Service ',
                'verbose_name_plural': ' Department Services ',
            },
        ),
        migrations.CreateModel(
            name='DepartmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners', 'company-banners'))),
                ('large', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-large', 'company-banners-large'))),
                ('medium', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-medium', 'company-banners-medium'))),
                ('small', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-small', 'company-banners-small'))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.department')),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departments Banner',
                'verbose_name_plural': 'Departments Banners',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.state')),
            ],
            options={
                'verbose_name_plural': ' Cities ',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name=main.models.PathRename('chats', 'chats'))),
                ('admin_read', models.BooleanField(default=False)),
                ('user_read', models.BooleanField(default=False)),
                ('is_order', models.BooleanField(default=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departmentservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners', 'company-banners'))),
                ('large', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-large', 'company-banners-large'))),
                ('medium', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-medium', 'company-banners-medium'))),
                ('small', models.ImageField(blank=True, null=True, upload_to=main.models.PathRename('company-banners-small', 'company-banners-small'))),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departments Banner',
                'verbose_name_plural': 'Departments Banners',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('reciever_first_name', models.CharField(max_length=30)),
                ('reciever_last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='WalletUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('symbol', 'country'), name='CurrencyUniqueConstraint'),
        ),
    ]
