# Generated by Django 3.2.3 on 2023-02-07 22:34

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('icon', models.FileField(upload_to=main.models.PathRename('notification-icon', 'notification-icon'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('icon', models.FileField(upload_to=main.models.PathRename('transaction-icon', 'transaction-icon'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='icon',
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='link1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='link2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='textbox',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='tips_deposit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='tips_deposit_online',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transactiontype'),
        ),
    ]
