# Generated by Django 3.2.3 on 2023-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='link1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='link2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='textbox',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='tips_deposit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositsettings',
            name='tips_deposit_online',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
