# Generated by Django 3.2.3 on 2023-02-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230207_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
