# Generated by Django 3.2.3 on 2023-01-28 14:18

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230128_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=6)),
                ('icon', models.FileField(upload_to=main.models.PathRename('transaction-icon', 'transaction-icon'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transactiontype'),
        ),
    ]
