# Generated by Django 3.2.3 on 2023-02-07 22:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_notificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('icon', models.FileField(upload_to=main.models.PathRename('notification-icon', 'notification-icon'))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
