# Generated by Django 3.2.3 on 2023-02-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230128_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
