# Generated by Django 3.2.3 on 2023-02-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.notificationtype'),
        ),
    ]
