# Generated by Django 3.2.3 on 2023-02-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_notification_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='icon_id',
        ),
    ]
