# Generated by Django 3.2.3 on 2023-02-09 06:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_type_notification_icon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.FileField(null=True, upload_to=main.models.PathRename('department-icon', 'department-icon')),
        ),
        migrations.AlterField(
            model_name='departmentservice',
            name='icon',
            field=models.FileField(null=True, upload_to=main.models.PathRename('service-icon', 'service-icon')),
        ),
    ]
