# Generated by Django 3.2.3 on 2023-02-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230209_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='background_item',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
