# Generated by Django 3.2.3 on 2023-01-24 21:00

import django.core.validators
from django.db import migrations, models
import insurance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=insurance.models.PathRename('Insurances', 'Insurances'))),
            ],
            options={
                'verbose_name': 'Health Insurance Company',
                'verbose_name_plural': 'Health Insurance Companies',
            },
        ),
        migrations.CreateModel(
            name='HealthInsurancePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('start_age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('end_age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('first_year', models.FloatField(null=True)),
                ('second_year', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Health Insurance Price Lists ',
            },
        ),
        migrations.CreateModel(
            name='HealthInsuranceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(default=insurance.models.rand, editable=False, max_length=10, unique=True)),
                ('passport_number', models.CharField(max_length=30)),
                ('cimlinc_number', models.CharField(max_length=30)),
                ('birthday_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('code', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_status', models.BooleanField(default=False)),
                ('period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('first_year_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('second_year_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('file', models.FileField(upload_to=insurance.models.PathRename('files', 'files'))),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthInsuranceUserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expiration_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
