# Generated by Django 3.2.3 on 2023-02-01 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import insurance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='addressDesc',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='apartmentNo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='buildingNo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='district',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='gender',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='insuranceStartDate',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='street',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.healthinsuranceuserdiscount'),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=insurance.models.PathRename('files', 'files')),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='first_year_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='second_year_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuraneRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
