# Generated by Django 3.2.3 on 2023-02-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20230201_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='insuranceStartDate',
        ),
    ]
