# Generated by Django 3.2.3 on 2023-02-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_remove_healthinsurancerequest_insurancestartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='addressDesc',
        ),
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='apartmentNo',
        ),
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='buildingNo',
        ),
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='healthinsurancerequest',
            name='street',
        ),
    ]
