# Generated by Django 3.2.3 on 2023-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20230201_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='addressDesc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='apartmentNo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='buildingNo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='street',
            field=models.CharField(default='', max_length=30),
        ),
    ]
