# Generated by Django 3.2.3 on 2023-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20230201_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='addressDesc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='apartmentNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='buildingNo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='street',
            field=models.CharField(max_length=30),
        ),
    ]
