# Generated by Django 3.2.3 on 2023-02-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20230201_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurancerequest',
            name='submit_date',
            field=models.DateField(null=True),
        ),
    ]
