# Generated by Django 3.2.3 on 2023-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_healthinsurancerequest_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
