# Generated by Django 3.2.3 on 2023-02-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_healthinsurancerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='healthinsurancerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
